### ISSUE TITLE
Gentle Warning on Incorrect Data File.

### ISSUE THREAD

**Issue by BenfengXu** [yaolu/Ordered-Prompt#1]
Great paper, and thanks for the opensource effort!

A gentle reminder:

The sst2 dataset provided in this `./data/sst2/test.jsonl` directory is incorrect, all instances in the [test.jsonl](https://github.com/yaolu/Ordered-Prompt/blob/main/data/sst2/test.jsonl) file are labeled as '0', while half of them should be '1'.

**Comment by yaolu** [comment]
Thank you for pointing this out. For evaluation, we use the dev_subsample file instead of test.jsonl. 

Reference: 
Section 4.1 in paper https://arxiv.org/abs/2104.08786
