### ISSUE TITLE
Clarification request `evaluate_file` import

### ISSUE THREAD

**Issue by ghbacct** [yaolu/Ordered-Prompt#2]
Hi Yao,

I'd like to request a clarification regarding the following import:
https://github.com/yaolu/Ordered-Prompt/blob/975d1e2f70ecac895a7ae236ae1962ec748d51b2/entropy.py#L4

The first suspect, [HuggingFace's evaluate library](https://github.com/huggingface/evaluate), does not implement a function called `evaluate_file`. 
Since this function is loading a custom pickle file, it seems that `evaluate` might be a custom module that might be missing from this repo? 

In this context what does `evaluate` refer to and where can I find the implementation of the function `evaluate_file`?

Thank you!

**Comment by yaolu** [comment]
Thanks for pointing this out. The missing file has been updated. 

https://github.com/yaolu/Ordered-Prompt/blob/main/evaluate.py
